from django.db import models
from django.contrib.auth.models import User

class hw(models.Model):
    uid=models.ForeignKey(User,on_delete=models.CASCADE)
    sa=models.CharField(max_length=600,default="")
    sb=models.CharField(max_length=600,default="")
    sc=models.CharField(max_length=600,default="")
    sd=models.CharField(max_length=600,default="")
    se=models.CharField(max_length=600,default="")
    sf=models.CharField(max_length=600,default="")
    sg=models.CharField(max_length=600,default="")
    sh=models.CharField(max_length=600,default="")
    si=models.CharField(max_length=600,default="")
    sj=models.CharField(max_length=600,default="")
    sk=models.CharField(max_length=600,default="")
    sl=models.CharField(max_length=600,default="")
    sm=models.CharField(max_length=600,default="")
    sn=models.CharField(max_length=600,default="")
    so=models.CharField(max_length=600,default="")
    sp=models.CharField(max_length=600,default="")
    sq=models.CharField(max_length=600,default="")
    sr=models.CharField(max_length=600,default="")
    ss=models.CharField(max_length=600,default="")
    st=models.CharField(max_length=600,default="")
    su=models.CharField(max_length=600,default="")
    sv=models.CharField(max_length=600,default="")
    sw=models.CharField(max_length=600,default="")
    sx=models.CharField(max_length=600,default="")
    sy=models.CharField(max_length=600,default="")
    sz=models.CharField(max_length=600,default="")
    ba=models.CharField(max_length=600,default="")
    bb=models.CharField(max_length=600,default="")
    bc=models.CharField(max_length=600,default="")
    bd=models.CharField(max_length=600,default="")
    be=models.CharField(max_length=600,default="")
    bf=models.CharField(max_length=600,default="")
    bg=models.CharField(max_length=600,default="")
    bh=models.CharField(max_length=600,default="")
    bi=models.CharField(max_length=600,default="")
    bj=models.CharField(max_length=600,default="")
    bk=models.CharField(max_length=600,default="")
    bl=models.CharField(max_length=600,default="")
    bm=models.CharField(max_length=600,default="")
    bn=models.CharField(max_length=600,default="")
    bo=models.CharField(max_length=600,default="")
    bp=models.CharField(max_length=600,default="")
    bq=models.CharField(max_length=600,default="")
    br=models.CharField(max_length=600,default="")
    bs=models.CharField(max_length=600,default="")
    bt=models.CharField(max_length=600,default="")
    bu=models.CharField(max_length=600,default="")
    bv=models.CharField(max_length=600,default="")
    bw=models.CharField(max_length=600,default="")
    bx=models.CharField(max_length=600,default="")
    by=models.CharField(max_length=600,default="")
    bz=models.CharField(max_length=600,default="")
    simg=models.ImageField(default='/static/default.png')
    
    def __str__(self):
        return '<%s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s>'%(self.uid,self.sa,self.sb,self.sc,self.sd,self.se,self.sf,self.sg,self.sh,self.si,self.sj,self.sk,self.sl,self.sm,self.sn,self.so,self.sp,self.sq,self.sr,self.ss,self.st,self.su,self.sv,self.sw,self.sx,self.sy,self.sz,self.ba,self.bb,self.bc,self.bd,self.be,self.bf,self.bg,self.bh,self.bi,self.bj,self.bk,self.bl,self.bm,self.bn,self.bo,self.bp,self.bq,self.br,self.bs,self.bt,self.bu,self.bv,self.bw,self.bx,self.by,self.bz,self.simg)