# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-28 04:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='hw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sa', models.CharField(default='', max_length=600)),
                ('sb', models.CharField(default='', max_length=600)),
                ('sc', models.CharField(default='', max_length=600)),
                ('sd', models.CharField(default='', max_length=600)),
                ('se', models.CharField(default='', max_length=600)),
                ('sf', models.CharField(default='', max_length=600)),
                ('sg', models.CharField(default='', max_length=600)),
                ('sh', models.CharField(default='', max_length=600)),
                ('si', models.CharField(default='', max_length=600)),
                ('sj', models.CharField(default='', max_length=600)),
                ('sk', models.CharField(default='', max_length=600)),
                ('sl', models.CharField(default='', max_length=600)),
                ('sm', models.CharField(default='', max_length=600)),
                ('sn', models.CharField(default='', max_length=600)),
                ('so', models.CharField(default='', max_length=600)),
                ('sp', models.CharField(default='', max_length=600)),
                ('sq', models.CharField(default='', max_length=600)),
                ('sr', models.CharField(default='', max_length=600)),
                ('ss', models.CharField(default='', max_length=600)),
                ('st', models.CharField(default='', max_length=600)),
                ('su', models.CharField(default='', max_length=600)),
                ('sv', models.CharField(default='', max_length=600)),
                ('sw', models.CharField(default='', max_length=600)),
                ('sx', models.CharField(default='', max_length=600)),
                ('sy', models.CharField(default='', max_length=600)),
                ('sz', models.CharField(default='', max_length=600)),
                ('ba', models.CharField(default='', max_length=600)),
                ('bb', models.CharField(default='', max_length=600)),
                ('bc', models.CharField(default='', max_length=600)),
                ('bd', models.CharField(default='', max_length=600)),
                ('be', models.CharField(default='', max_length=600)),
                ('bf', models.CharField(default='', max_length=600)),
                ('bg', models.CharField(default='', max_length=600)),
                ('bh', models.CharField(default='', max_length=600)),
                ('bi', models.CharField(default='', max_length=600)),
                ('bj', models.CharField(default='', max_length=600)),
                ('bk', models.CharField(default='', max_length=600)),
                ('bl', models.CharField(default='', max_length=600)),
                ('bm', models.CharField(default='', max_length=600)),
                ('bn', models.CharField(default='', max_length=600)),
                ('bo', models.CharField(default='', max_length=600)),
                ('bp', models.CharField(default='', max_length=600)),
                ('bq', models.CharField(default='', max_length=600)),
                ('br', models.CharField(default='', max_length=600)),
                ('bs', models.CharField(default='', max_length=600)),
                ('bt', models.CharField(default='', max_length=600)),
                ('bu', models.CharField(default='', max_length=600)),
                ('bv', models.CharField(default='', max_length=600)),
                ('bw', models.CharField(default='', max_length=600)),
                ('bx', models.CharField(default='', max_length=600)),
                ('by', models.CharField(default='', max_length=600)),
                ('bz', models.CharField(default='', max_length=600)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
